# Pull official base image
FROM node:13.10-buster-slim

# Set working directory
WORKDIR /usr/src/todo-spa

# Install and cache the app dependencies
COPY package*.json /usr/src/todo-spa/
RUN yarn install
COPY ./ .
RUN yarn run build
COPY ./dist /usr/src/todo-spa/
